### ISSUE TITLE
cannot use nat in docker-mininet

### ISSUE THREAD

**Issue by allewwaly** [iwaseyusuke/docker-mininet#7]
After installed docker-mininet, I tried to start mininet with `--nat` option. However I got the following error message:
```
root@ada1905bfaf8:~# mn --nat
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

IOError: [Errno 2] No such file or directory: '/etc/network/interfaces'
--------------------------------------------------------------------------------
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
( ip link del s1-eth1;ip link del s1-eth2;ip link del s1-eth3;ip link del nat0-eth0;ip link del nat0-eth0;ip link del s1-eth3 ) 2> /dev/null
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.

```
Directly running `mn`  works fine.

**Comment by allewwaly** [comment]
The debug infomation
```
root@ada1905bfaf8:~# mn --nat -v debug
*** errRun: ['which', 'controller'] 
  1*** errRun: ['which', 'ovs-controller'] 
  1*** errRun: ['which', 'test-controller'] 
  1*** errRun: ['which', 'ovs-testcontroller'] 
/usr/bin/ovs-testcontroller
  0*** errRun: ['grep', '-c', 'processor', '/proc/cpuinfo'] 
4
  0*** Setting resource limits
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** errRun: ['which', 'ovs-controller'] 
  1*** errRun: ['which', 'test-controller'] 
  1*** errRun: ['which', 'ovs-testcontroller'] 
/usr/bin/ovs-testcontroller
  0*** errRun: ['which', 'mnexec'] 
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig'] 
/sbin/ifconfig
  0*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet'] 
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6653',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** errRun: ['which', 'mnexec'] 
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig'] 
/sbin/ifconfig
  0*** h1 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
h1 *** h2 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
h2 
*** Adding switches:
*** errRun: ['which', 'ovs-vsctl'] 
/usr/bin/ovs-vsctl
  0*** errRun: ['ovs-vsctl', '-t', '1', 'show'] 
da5f398b-351c-40a2-a9d1-face87f1abd3
    Manager "ptcp:6640"
    ovs_version: "2.9.0"
  0*** errRun: ['ovs-vsctl', '--version'] 
ovs-vsctl (Open vSwitch) 2.9.0
DB Schema 7.15.1
  0*** s1 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m

added intf lo (0) to node s1
*** s1 : ('ifconfig', 'lo', 'up')
s1 
*** Adding links:
*** h1 : ('ip link add name h1-eth0 address 26:c4:67:86:88:ad type veth peer name s1-eth1 address 02:be:70:e6:33:77 netns 666',)

added intf h1-eth0 (0) to node h1
moving h1-eth0 into namespace for h1 
*** h1 : ('ifconfig', 'h1-eth0', 'up')

added intf s1-eth1 (1) to node s1
*** s1 : ('ifconfig', 's1-eth1', 'up')
(h1, s1) *** h2 : ('ip link add name h2-eth0 address ca:8d:69:b9:9d:7d type veth peer name s1-eth2 address 92:40:c0:ce:2c:f8 netns 666',)

added intf h2-eth0 (0) to node h2
moving h2-eth0 into namespace for h2 
*** h2 : ('ifconfig', 'h2-eth0', 'up')

added intf s1-eth2 (2) to node s1
*** s1 : ('ifconfig', 's1-eth2', 'up')
(h2, s1) 
*** Configuring hosts
h1 *** h1 : ('ifconfig', 'h1-eth0', '10.0.0.1/8', 'up')
*** h1 : ('ifconfig lo up',)
h2 *** h2 : ('ifconfig', 'h2-eth0', '10.0.0.2/8', 'up')
*** h2 : ('ifconfig lo up',)

*** errRun: ['which', 'mnexec'] 
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig'] 
/sbin/ifconfig
  0*** nat0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** nat0 : ('sysctl -n net.ipv4.ip_forward',)
1
*** nat0 : ('ip link add name nat0-eth0 address f6:e8:b9:d5:87:a0 type veth peer name s1-eth3 address 5a:57:bc:af:61:74 netns 666',)

added intf nat0-eth0 (0) to node nat0
*** nat0 : ('ifconfig', 'nat0-eth0', 'up')

added intf s1-eth3 (3) to node s1
*** s1 : ('ifconfig', 's1-eth3', 'up')
*** h1 : ('ip route del default; ip route add default', 'via 10.0.0.3')
RTNETLINK answers: No such process
*** h2 : ('ip route del default; ip route add default', 'via 10.0.0.3')
RTNETLINK answers: No such process
*** nat0 : ('ifconfig', 'nat0-eth0', '10.0.0.3/8', 'up')
*** nat0 : ('ifconfig lo up',)
*** nat0 : ('iptables -I FORWARD', '-i', <Intf nat0-eth0>, '-d', '10.0.0.0/8', '-j DROP')
bash: iptables: command not found
*** nat0 : ('iptables -A FORWARD', '-i', <Intf nat0-eth0>, '-s', '10.0.0.0/8', '-j ACCEPT')
bash: iptables: command not found
*** nat0 : ('iptables -A FORWARD', '-o', <Intf nat0-eth0>, '-d', '10.0.0.0/8', '-j ACCEPT')
bash: iptables: command not found
*** nat0 : ('iptables -t nat -A POSTROUTING', '-s', '10.0.0.0/8', "'!'", '-d', '10.0.0.0/8', '-j MASQUERADE')
bash: iptables: command not found
*** nat0 : ('sysctl net.ipv4.ip_forward=1',)
net.ipv4.ip_forward = 1
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

IOError: [Errno 2] No such file or directory: '/etc/network/interfaces'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/mn", line 399, in <module>
    MininetRunner()
  File "/usr/bin/mn", line 135, in __init__
    self.begin()
  File "/usr/bin/mn", line 361, in begin
    nat.configDefault()
  File "/usr/lib/python2.7/dist-packages/mininet/node.py", line 590, in configDefault
    self.config( **self.params )
  File "/usr/lib/python2.7/dist-packages/mininet/nodelib.py", line 122, in config
    config = open( cfile ).read()
IOError: [Errno 2] No such file or directory: '/etc/network/interfaces'

*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** errRun: ['pkill', '-9', '-f', 'mnexec.*socat'] 
  1*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
( ip link del s1-eth1;ip link del s1-eth2;ip link del s1-eth3;ip link del nat0-eth0;ip link del nat0-eth0;ip link del s1-eth3 ) 2> /dev/null
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.

```

**Comment by allewwaly** [comment]
After I manually created `/etc/network/interface`, the mininet started, however the hosts still cannot access the internet.
```
root@ada1905bfaf8:~# mn --nat -v debug
*** errRun: ['which', 'controller'] 
  1*** errRun: ['which', 'ovs-controller'] 
  1*** errRun: ['which', 'test-controller'] 
  1*** errRun: ['which', 'ovs-testcontroller'] 
/usr/bin/ovs-testcontroller
  0*** errRun: ['grep', '-c', 'processor', '/proc/cpuinfo'] 
4
  0*** Setting resource limits
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** errRun: ['which', 'ovs-controller'] 
  1*** errRun: ['which', 'test-controller'] 
  1*** errRun: ['which', 'ovs-testcontroller'] 
/usr/bin/ovs-testcontroller
  0*** errRun: ['which', 'mnexec'] 
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig'] 
/sbin/ifconfig
  0*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet'] 
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6653',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts:
*** errRun: ['which', 'mnexec'] 
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig'] 
/sbin/ifconfig
  0*** h1 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
h1 *** h2 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
h2 
*** Adding switches:
*** errRun: ['which', 'ovs-vsctl'] 
/usr/bin/ovs-vsctl
  0*** errRun: ['ovs-vsctl', '-t', '1', 'show'] 
da5f398b-351c-40a2-a9d1-face87f1abd3
    Manager "ptcp:6640"
    ovs_version: "2.9.0"
  0*** errRun: ['ovs-vsctl', '--version'] 
ovs-vsctl (Open vSwitch) 2.9.0
DB Schema 7.15.1
  0*** s1 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m

added intf lo (0) to node s1
*** s1 : ('ifconfig', 'lo', 'up')
s1 
*** Adding links:
*** h1 : ('ip link add name h1-eth0 address 2e:3a:d8:12:36:fb type veth peer name s1-eth1 address ee:d8:09:d2:e9:b3 netns 1866',)

added intf h1-eth0 (0) to node h1
moving h1-eth0 into namespace for h1 
*** h1 : ('ifconfig', 'h1-eth0', 'up')

added intf s1-eth1 (1) to node s1
*** s1 : ('ifconfig', 's1-eth1', 'up')
(h1, s1) *** h2 : ('ip link add name h2-eth0 address ae:77:bc:cb:37:d8 type veth peer name s1-eth2 address 96:d4:ac:f9:25:97 netns 1866',)

added intf h2-eth0 (0) to node h2
moving h2-eth0 into namespace for h2 
*** h2 : ('ifconfig', 'h2-eth0', 'up')

added intf s1-eth2 (2) to node s1
*** s1 : ('ifconfig', 's1-eth2', 'up')
(h2, s1) 
*** Configuring hosts
h1 *** h1 : ('ifconfig', 'h1-eth0', '10.0.0.1/8', 'up')
*** h1 : ('ifconfig lo up',)
h2 *** h2 : ('ifconfig', 'h2-eth0', '10.0.0.2/8', 'up')
*** h2 : ('ifconfig lo up',)

*** errRun: ['which', 'mnexec'] 
/usr/bin/mnexec
  0*** errRun: ['which', 'ifconfig'] 
/sbin/ifconfig
  0*** nat0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** nat0 : ('sysctl -n net.ipv4.ip_forward',)
1
*** nat0 : ('ip link add name nat0-eth0 address 92:57:bf:f0:ce:57 type veth peer name s1-eth3 address 4a:b4:4b:bc:9f:43 netns 1866',)

added intf nat0-eth0 (0) to node nat0
*** nat0 : ('ifconfig', 'nat0-eth0', 'up')

added intf s1-eth3 (3) to node s1
*** s1 : ('ifconfig', 's1-eth3', 'up')
*** h1 : ('ip route del default; ip route add default', 'via 10.0.0.3')
RTNETLINK answers: No such process
*** h2 : ('ip route del default; ip route add default', 'via 10.0.0.3')
RTNETLINK answers: No such process
*** nat0 : ('ifconfig', 'nat0-eth0', '10.0.0.3/8', 'up')
*** nat0 : ('ifconfig lo up',)
*** nat0 : ('iptables -I FORWARD', '-i', <Intf nat0-eth0>, '-d', '10.0.0.0/8', '-j DROP')
bash: iptables: command not found
*** nat0 : ('iptables -A FORWARD', '-i', <Intf nat0-eth0>, '-s', '10.0.0.0/8', '-j ACCEPT')
bash: iptables: command not found
*** nat0 : ('iptables -A FORWARD', '-o', <Intf nat0-eth0>, '-d', '10.0.0.0/8', '-j ACCEPT')
bash: iptables: command not found
*** nat0 : ('iptables -t nat -A POSTROUTING', '-s', '10.0.0.0/8', "'!'", '-d', '10.0.0.0/8', '-j MASQUERADE')
bash: iptables: command not found
*** nat0 : ('sysctl net.ipv4.ip_forward=1',)
net.ipv4.ip_forward = 1
*** nat0 : ('service network-manager restart',)
network-manager: unrecognized service
*** Starting controller
c0 *** errRun: ['which', '/usr/bin/ovs-testcontroller'] 
/usr/bin/ovs-testcontroller
  0*** c0 : ('/usr/bin/ovs-testcontroller -v ptcp:6653 1>/tmp/c0.log 2>/tmp/c0.log &',)

*** Starting 1 switches
s1 ...*** errRun: ovs-vsctl -- --id=@s1c0 create Controller target=\"tcp:127.0.0.1:6653\" max_backoff=1000 -- --id=@s1-listen create Controller target=\"ptcp:6654\" max_backoff=1000 -- --if-exists del-br s1 -- add-br s1 -- set bridge s1 controller=[@s1c0,@s1-listen] other_config:datapath-id=0000000000000001 fail_mode=secure other-config:disable-in-band=true -- add-port s1 s1-eth1 -- set Interface s1-eth1 ofport_request=1 -- add-port s1 s1-eth2 -- set Interface s1-eth2 ofport_request=2 -- add-port s1 s1-eth3 -- set Interface s1-eth3 ofport_request=3 
9ac9fae9-0083-4b1d-b275-166cad80c608
256049e1-427a-4824-877c-3f8e07e65149
  0
*** Starting CLI:
*** errRun: ['stty', 'echo', 'sane', 'intr', '^C'] 
  0mininet> h1 ping h2
*** errRun: ['stty', '-icanon', 'min', '1'] 
  0PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
64 bytes from 10.0.0.2: icmp_seq=1 ttl=64 time=1.84 ms
64 bytes from 10.0.0.2: icmp_seq=2 ttl=64 time=0.226 ms
64 bytes from 10.0.0.2: icmp_seq=3 ttl=64 time=0.028 ms
64 bytes from 10.0.0.2: icmp_seq=4 ttl=64 time=0.037 ms
64 bytes from 10.0.0.2: icmp_seq=5 ttl=64 time=0.037 ms
64 bytes from 10.0.0.2: icmp_seq=6 ttl=64 time=0.031 ms
64 bytes from 10.0.0.2: icmp_seq=7 ttl=64 time=0.102 ms
64 bytes from 10.0.0.2: icmp_seq=8 ttl=64 time=0.034 ms
^CsendInt: writing chr(3)

--- 10.0.0.2 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7149ms
rtt min/avg/max/mdev = 0.028/0.292/1.842/0.589 ms
mininet> h1 ping baidu.com
*** errRun: ['stty', '-icanon', 'min', '1'] 
  0
^CsendInt: writing chr(3)
```

**Comment by ToJen** [comment]
Can you share your working Dockerfile?

**Comment by iwaseyusuke** [comment]
Very sorry for the delayed response. Because it is 4+ years since I left the OpenFlow related project, and currently I don’t have enough environment to develop on this repo.

Even though the cause of this issue seems not to be on this Dockerfile, but on the changes like Ubuntu has moved onto "netplan" from Ubuntu 18.04.

**Comment by iwaseyusuke** [comment]
Does the following solve this problem?
* install `iptables`
* install `dnsutils` (convenience for network trouble shooting)
* create an empty `/etc/network/interfaces` file

logs:
```sh
$ docker run -it --rm --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /lib/modules:/lib/modules iwaseyusuke/mininet
 * /etc/openvswitch/conf.db does not exist
 * Creating empty database /etc/openvswitch/conf.db
 * Starting ovsdb-server
 * Configuring Open vSwitch system IDs
 * Starting ovs-vswitchd
 * Enabling remote OVSDB managers
root@5da88e2af39d:~# apt update && apt install  -y iptables dnsutils
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/universe Sources [366 kB]
...(snip)...
root@5da88e2af39d:~# touch /etc/network/interfaces
root@5da88e2af39d:~# mn --nat
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2
*** Adding switches:
s1
*** Adding links:
(h1, s1) (h2, s1)
*** Configuring hosts
h1 h2
*** Adding "iface nat0-eth0 inet manual" to /etc/network/interfaces
*** Starting controller
c0
*** Starting 1 switches
s1 ...
*** Starting CLI:
mininet> h1 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=102 time=33.3 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=102 time=29.8 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=102 time=32.5 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 29.868/31.903/33.306/1.472 ms
mininet>
```

If it works fine, I will push this fix to upstream.
